### PR TITLE
Create Meme Generator using Javascript

### PR DESCRIPTION
**Pull request by Pawan85**
I am Pawan.

### CODE REVIEW

**Comment by ayushdubey003** [comment]
@Pawan85 what does your code aim to achieve? Can you provide a brief intro to the same?

**Comment by Mac306** [comment]
It just like website which make memes.

**Comment by ayushdubey003** [comment]
Cool but this project doesn't aim to do this.
Closing this pull request!

**Comment by Mac306** [comment]
Are u from Jamshedpur?

**Pull request closed without merging**
